In [1]:
import nltk
import pandas as ps
import numpy as pn
import warnings
from sklearn.preprocessing import MinMaxScaler

In [2]:
fd=ps.read_csv(r"C:/Users/Harshit/Downloads/moviereviews.tsv",sep="\t")

In [3]:
fd.head()

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [4]:
fd.shape

(2000, 2)

In [5]:
fd.isnull().sum()/len(fd)*100

label     0.00
review    1.75
dtype: float64

In [6]:
fd.dropna(inplace=True)

blanks=[]
for x,y,z in fd.itertuples():
    if type(z)==str:
        if z.isspace():
            blanks.append(x)
fd.drop(blanks,inplace=True)

In [7]:
fd.isnull().sum()/len(fd)*100

label     0.0
review    0.0
dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score

In [9]:
X = fd.drop(columns = ['label'])
y = fd['label']

In [10]:
train_set,test_set=train_test_split(fd,test_size=0.2,random_state=42)
print(f"Train Set: {len(train_set)}\nTest Set: {len(test_set)}\n")

Train Set: 1550
Test Set: 388



In [11]:
from sklearn.preprocessing import LabelEncoder

cat_cols=["review","label"]
le=LabelEncoder()
for x in cat_cols:
    fd[x]=le.fit_transform(fd[x])

In [12]:
fd.head()
a=fd.columns
a

Index(['label', 'review'], dtype='object')

In [13]:
scaler=MinMaxScaler()

In [14]:
fd[a]=scaler.fit_transform(fd[a])
fd

label    review
0       0.0  0.331957
1       0.0  0.685080
2       1.0  0.855447
3       1.0  0.110480
4       0.0  0.556014
...     ...       ...
1995    1.0  0.360351
1996    1.0  0.464636
1997    1.0  0.824471
1998    1.0  0.376355
1999    1.0  0.090346

[1938 rows x 2 columns]

In [15]:
fd.head()

label    review
0    0.0  0.331957
1    0.0  0.685080
2    1.0  0.855447
3    1.0  0.110480
4    0.0  0.556014

In [16]:
from sklearn.preprocessing import StandardScaler 
from statsmodels.stats.outliers_influence import variance_inflation_factor

scalar = StandardScaler()
X_scaled = scalar.fit_transform(fd)

In [17]:
X_scaled

array([[-1.        , -0.581819  ],
       [-1.        ,  0.64080526],
       [ 1.        ,  1.23066784],
       ...,
       [ 1.        ,  1.1234201 ],
       [ 1.        , -0.42809724],
       [ 1.        , -1.41835139]])

In [18]:
X=fd["review"]
y=fd['label']

In [19]:
x_train,x_test,y_train,y_test = train_test_split(X_scaled,y, test_size= 0.25, random_state =1)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
logmodel=LogisticRegression()

In [22]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [23]:
prediction=logmodel.predict(x_test)

In [24]:
from sklearn.metrics import classification_report

In [25]:
classification_report(y_test,prediction)

'              precision    recall  f1-score   support\n\n         0.0       1.00      1.00      1.00       249\n         1.0       1.00      1.00      1.00       236\n\n    accuracy                           1.00       485\n   macro avg       1.00      1.00      1.00       485\nweighted avg       1.00      1.00      1.00       485\n'

In [28]:
# Assuming you have true labels and predicted labels stored in true_labels and predicted_labels variables

confusion_matrix = confusion_matrix(y_test, prediction)

true_positive =confusion_matrix[0,0]
false_positive =confusion_matrix[0,1]
false_negative =confusion_matrix[1,0]
true_negative =confusion_matrix[1,1]
print('True-Negative=',true_negative)
print('True-Positive=',true_positive)
print('False-Negative=',false_negative)
print('False-Positive=',false_positive)
from sklearn.metrics import confusion_matrix

# Assuming you have true labels and predicted labels stored in true_labels and predicted_labels variables
confusion_matrix_data = confusion_matrix(y_test, prediction)

# Accessing the elements of the confusion matrix
# true_positive = confusion_matrix_data[0, 0]
# false_positive = confusion_matrix_data[0, 1]
# false_negative = confusion_matrix_data[1, 0]
# true_negative =confusion_matrix_data[1, 1]
# print('True-Negative=',true_negative)
# print('True-Positive=',true_positive)
# print('False-Negative=',false_negative)
# print('False-Positive=',false_positive)

True-Negative= 236
True-Positive= 249
False-Negative= 0
False-Positive= 0


In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix=confusion_matrix(y_test,prediction)
confusion_matrix

array([[249,   0],
       [  0, 236]], dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
Accuracy = (true_positive + true_negative) / (true_positive +false_positive + false_negative + true_negative)
Accuracy

1.0

In [55]:
Precision = true_positive/(true_positive+false_positive)
Precision

1.0

In [34]:
# Recall
Recall = true_positive/(true_positive+false_negative)
Recall

1.0

In [35]:
# F1 Score
F1_Score = 2*(Recall * Precision) / (Recall + Precision)
F1_Score

1.0

In [36]:
from sklearn.svm import SVC

In [37]:
fd[a]=scaler.fit_transform(fd[a])

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

In [48]:
from sklearn.svm import SVC
import numpy as pn

model = SVC(C=1)

# Convert the Series to a NumPy array and reshape it
X_train_reshaped = X_train.values.reshape(-1, 1)

# Fit the model with the reshaped data
model.fit(X_train_reshaped, y_train)



SVC(C=1)

In [54]:
from sklearn import metrics

# Assuming you have true labels and predicted labels stored in y_test and prediction variables
# Ensure the arrays have the same shape
y_test = y_test[:485]
prediction = prediction[:485]

# Calculate accuracy
accuracy = metrics.accuracy_score(y_test, prediction)
print("Accuracy:", accuracy)

# Calculate precision
precision = metrics.precision_score(y_test, prediction)
print("Precision:", precision)


Accuracy: 0.4927835051546392
Precision: 0.4491525423728814


In [56]:
classification_report(y_test,prediction)

'              precision    recall  f1-score   support\n\n         0.0       0.53      0.51      0.52       263\n         1.0       0.45      0.48      0.46       222\n\n    accuracy                           0.49       485\n   macro avg       0.49      0.49      0.49       485\nweighted avg       0.50      0.49      0.49       485\n'

In [ ]:
# From Here we have use Pipeline to see whether this should enhance my model.

In [19]:
import sklearn

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

In [22]:
vect = TfidfVectorizer()

In [23]:
pipe = vect.fit_transform(X_train)

In [24]:
# Naïve Bayes:
pipe1 = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),
])

# Linear SVC:
pipe2 = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

In [26]:
pipe1.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [27]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [38]:
prediction=pipe1.predict(X_test)

In [42]:
from sklearn.metrics import classification_report

In [ ]:
# As we can clearly see that our accuracy and almost all the scores has increased by using tfid vectorizer

In [44]:
classification_report(y_test,prediction)

'              precision    recall  f1-score   support\n\n         neg       0.86      0.78      0.82       307\n         pos       0.78      0.86      0.82       275\n\n    accuracy                           0.82       582\n   macro avg       0.82      0.82      0.82       582\nweighted avg       0.82      0.82      0.82       582\n'

In [45]:
confusion_matrix=confusion_matrix(y_test,prediction)
confusion_matrix

array([[239,  68],
       [ 39, 236]], dtype=int64)